services:
  app:
    image: splittink:latest
    container_name: splittink-app
    restart: unless-stopped
    ports:
      - "8123:80"
    volumes:
      - ./.env.production:/var/www/.env
      - ./logs:/var/log
      - ./database/database.sqlite:/var/www/database/database.sqlite
      - ./storage/logs/laravel.log:/var/www/storage/logs/laravel.log
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
